contrib/build.lua
contrib/testfiles/ctex001.lvt
contrib/testfiles/ctex001.ptex.tlg
contrib/testfiles/ctex001.tlg
contrib/testfiles/ctex001.uptex.tlg
contrib/testfiles/fontspec001.lvt
contrib/testfiles/unicode-math001.lvt
texlive.sh

This test is only to indicate running without any errors.
@LiamHuang0205 @leo-liu

Add a basic test for ctex

---

contrib/testfiles/ctex002.luatex.tlg
contrib/testfiles/ctex002.lvt
contrib/testfiles/ctex002.ptex.tlg
contrib/testfiles/ctex002.tlg
contrib/testfiles/ctex002.uptex.tlg
contrib/testfiles/ctex002.xetex.tlg

This pull request close @LiamHuang0205's #276.

Add another test for ctex.

---

l3build/l3build.lua

New pull request following #265.

Copy recursively

---

l3kernel/l3drivers.dtx

Remove three unsuitable \exp_not:N in l3drivers

---

l3kernel/l3box.dtx

`\subsection` -> `\section` for Affine transformations

fix typo: update l3box.dtx

---

l3kernel/l3candidates.dtx

`\subsection` -> `\subsubsection`

Update l3candidates.dtx [ci skip]

---

l3kernel/l3file.dtx
l3kernel/l3msg.dtx

Same as https://github.com/latex3/latex3/commit/b43cf910a4901ed052a2a3ec864153036249347b, modulo messing up line endings.

Use \cs_if_exist_use:N instead of \use:c for trace

---

l3kernel/l3prefixes.csv

Hello,
Please find this request for registering a prefix, as a pull request.
Best,
Arthur

Registering prefix for Polyglossia.

---

l3kernel/l3basics.dtx

Hello,
I believe these two comments in `l3basics.dtx` need a little update. Thanks!

Update two comments

---

l3kernel/doc/l3prefixes.csv

following your request here: https://github.com/berleon/emojicite/issues/1
Best,
Leon

Add emojicite to l3prefixes.csv

---

l3experimental/l3pdf/l3pdf.dtx
l3experimental/l3pdf/testfiles/m3pdf002.lvt
l3experimental/l3pdf/testfiles/m3pdf002.tlg

#711 (I didn't add a backend version as suggested in the issue as the backend is loaded later, so can not be the original.)

add test for object existence, issue #711

---

l3kernel/doc/l3prefixes.csv

Register pdfoverlay prefix [ci skip]

---

l3experimental/CHANGELOG.md
l3experimental/l3color/l3color.dtx
l3experimental/l3color/testfiles/m3color002.lvt
l3experimental/l3color/testfiles/m3color002.tlg
l3experimental/l3draw/l3draw-state.dtx

Currently just for HTML, other targets to be discussed

Add \color_export:nn(n)N

---

l3kernel/doc/l3prefixes.csv

I'd like to add two prefixes, since this is no big deal I did it in one pull request but could also split it up. This is done in preparation for releases via CTAN. 
I was wondering if I should add a note but the URLs should explain enough.
And since I am writing now. Thanks a lot for your work!

Register the prefixes chaos + kivitendo

---

l3kernel/CHANGELOG.md
l3kernel/l3keys.dtx
l3kernel/l3prg.dtx
l3kernel/l3regex.dtx
l3kernel/l3str.dtx
l3kernel/l3tl.dtx
l3kernel/l3token.dtx
l3kernel/testfiles/m3prg005.lvt
l3kernel/testfiles/m3prg005.tlg

Various documentation improvements, also incidentally adding `\bool_to_str:N`.

Gh1010 doc

---

l3kernel/doc/l3prefixes.csv

I would like to register some prefixes for my packages. Thanks!

Register prefixes codehigh, fun, ninecolors, tblr

---

l3kernel/doc/l3prefixes.csv

Update l3prefixes.csv [ci skip]

---

l3kernel/l3basics.dtx

see https://github.com/latex3/latex3/issues/1150#issuecomment-1465128172

Mention corresponding primitive names for `\if_cs_exist:[Nw]`

---

l3kernel/CHANGELOG.md
l3kernel/l3text-case.dtx
l3kernel/l3text.dtx
l3kernel/testfiles/m3text002.luatex.tlg
l3kernel/testfiles/m3text002.lvt
l3kernel/testfiles/m3text002.ptex.tlg
l3kernel/testfiles/m3text002.tlg
l3kernel/testfiles/m3text002.uptex.tlg
l3kernel/testfiles/m3text002.xetex.tlg

This will be the basis for fixing latex3/latex2e#1033. The key question is does the interface here make sense: codepoing by number, inserted tokens 'as is'.

Add case changing customisation

---

l3kernel/CHANGELOG.md
l3kernel/l3coffins.dtx

https://github.com/latex3/latex3/issues/442

A way to forget coffin poles

---

l3kernel/CHANGELOG.md
l3kernel/l3file.dtx

Add \iow_shell_open:Nn (closes #1122)

---

l3kernel/l3msg.dtx

introduced in 6954357 (Expand coverage of variants (see #<span></span>1257), 2023-08-23)

Drop a duplicate line

---

l3kernel/CHANGELOG.md
l3kernel/l3tl.dtx

Add variants `\tl_if_single:c(TF)` and `\tl_if_single_p:c`

---

l3experimental/CHANGELOG.md
l3experimental/l3benchmark/testfiles/m3benchmark002.lvt

to hopefully avoid getting "0 seconds (0 ops)"
Closes #1274

Slowdown a l3benchmark slow branch code, slightly

---

l3kernel/doc/l3obsolete.txt

Found when checking things for #1333.

Tidy entries in `l3obsolete.txt`

---

l3kernel/CHANGELOG.md
l3kernel/l3str.dtx

Add `\c_empty_str`

---

l3kernel/CHANGELOG.md
l3kernel/l3bitset.dtx
l3kernel/testfiles/m3bitset001.lvt
l3kernel/testfiles/m3bitset001.tlg
l3kernel/testfiles/m3bitset002.lvt
l3kernel/testfiles/m3bitset002.tlg

Document and test `\bitset_show_named_index:N`, and add its `log` variant

---

l3kernel/CHANGELOG.md

Refer to addressed issue in Changelog

---

l3experimental/l3draw/l3draw-softpath.dtx
l3kernel/CHANGELOG.md
l3kernel/doc/l3obsolete.txt
l3kernel/l3candidates.dtx
l3kernel/l3deprecation.dtx
l3kernel/l3regex.dtx
l3kernel/l3tl-build.dtx
l3kernel/testfiles/m3tl-build001.lvt
l3kernel/testfiles/m3tl-build001.tlg

Parallel to https://github.com/latex3/latex3/pull/1302

Move \tl_build_get_intermediate:NN to stable

---

l3kernel/CHANGELOG.md

Polish Changelog

---

l3kernel/CHANGELOG.md
l3kernel/l3tl.dtx

Clarify behavior of `\tl_if_novalue:n(TF)`

---

l3kernel/CHANGELOG.md

Introduced in #1405, my just merged PR. 😄

Typo in Changelog

---

l3kernel/l3regex.dtx

To be consistent with the others.
Package: expl3 2024-01-04
TeX Live 2023
pdfTeX

Update l3regex.dtx , Maybe a typo

---

l3experimental/CHANGELOG.md
l3experimental/l3draw/l3draw-paths.dtx
l3experimental/l3draw/testfiles/m3draw003.lvt
l3experimental/l3draw/testfiles/m3draw003.tlg

Fix shifts not applied to rectangle in l3draw

---

l3experimental/CHANGELOG.md
l3experimental/l3draw/l3draw-paths.dtx
l3experimental/l3draw/testfiles/m3draw003.etex-dvips.tlg
l3experimental/l3draw/testfiles/m3draw003.etex-dvisvgm.tlg
l3experimental/l3draw/testfiles/m3draw003.lvt
l3experimental/l3draw/testfiles/m3draw003.tlg
l3experimental/l3draw/testfiles/m3draw003.uptex.tlg
l3experimental/l3draw/testfiles/m3draw003.xetex.tlg

Fix out-of-boundary grid lines in l3draw

---

l3kernel/l3basics.dtx

Fix typo in documentation

---

l3experimental/l3draw/l3draw-transforms.dtx

Reset active matrix marker in `\draw_transform_matrix_reset:`

---

l3kernel/CHANGELOG.md
l3kernel/l3basics.dtx
l3kernel/l3cctab.dtx
l3kernel/testfiles/m3cctab002.luatex.tlg
l3kernel/testfiles/m3cctab002.lvt
l3kernel/testfiles/m3cctab002.tlg
l3kernel/testfiles/m3cctab002.xetex.tlg

Avoid "Inconsistent local/global assignment" errors in \cctab_const:Nn

---

l3kernel/CHANGELOG.md
l3kernel/l3file.dtx

They were added in #1516.
Also added a Changelog entry for #1516.

Add macro env for \__kernel_iow_open:Nn and No

---

l3kernel/l3fparray.dtx
l3kernel/l3intarray.dtx

As a preparation for adding `\intarray_if_exist:N(TF)` raised in https://github.com/latex3/latex3/pull/1524#pullrequestreview-1970356248.

Classify intarray and fparray fun. docs into sections

---

l3kernel/CHANGELOG.md
l3kernel/l3fparray.dtx
l3kernel/l3intarray.dtx

`\intarray_if_exist:NF` is required in #1524, see https://github.com/latex3/latex3/pull/1524#pullrequestreview-1970356248.

Add \intarray_if_exist:N(TF) and \fparray_if_exist:N(TF)

---

l3kernel/doc/l3prefixes.csv

- https://github.com/qinglee/wrapstuff
- https://ctan.org/pkg/wrapstuff

Register prefix "wstf" for wrapstuff

---

l3kernel/CHANGELOG.md
l3kernel/l3keys.dtx
l3kernel/testfiles/m3keys004.lvt
l3kernel/testfiles/m3keys004.tlg

Need a Changelog entry?
_Update:_ Added one (about doc improvement) so there's something to (pre)release.

\keys_set_groups:nnn(n)N: fix typos, add syntaxes and tests

---

l3kernel/doc/l3prefixes.csv

This PR registers the prefix ~~`expl3tools`~~ `expltools`.

Register prefix `expltools`

---

l3kernel/doc/l3prefixes.csv

Register prefix "moremath"

---

l3kernel/CHANGELOG.md
l3kernel/l3file.dtx

Fix recursive doc of `\file_if_exist:n(TF)`

---

l3kernel/l3clist.dtx

Found when preparing https://github.com/James-Yu/LaTeX-Workshop/pull/4343.

Add missing comma

---

l3kernel/l3doc.dtx

See https://github.com/latex3/latex3/pull/1578#discussion_r1728457597.

Switch from e to o-type expansion

---

l3experimental/l3graphics/l3graphics.dtx
l3kernel/l3regex.dtx
l3kernel/l3tl.dtx

fix small typos

---

l3kernel/testfiles/m3color001.lvt
l3kernel/testfiles/m3color001.tlg

Add tests for initial color "."

---

l3kernel/CHANGELOG.md
l3kernel/l3tl-analysis.dtx
l3kernel/testfiles/m3regex012.tlg
l3kernel/testfiles/m3tl-analysis001.luatex.tlg
l3kernel/testfiles/m3tl-analysis001.lvt
l3kernel/testfiles/m3tl-analysis001.tlg
l3kernel/testfiles/m3tl-analysis001.xetex.tlg

Add trailing period to `\tl_analysis_log:(N|n)`

---

l3kernel/l3tl.dtx

Revert "Update l3tl.dtx"

---

l3kernel/testfiles/m3names001.lvt

Enable tests for 3 TL'25-only names

---

l3kernel/l3doc.dtx

- `\l__codedoc_variants_prop`
- `\c__codedoc_iow_rule_tl`
- `\c__codedoc_iow_mid_rule_tl`

Drop unused variables from l3doc
