latex3/latex3

- l3kernel/l3names.dtx
`\luatexsuppressfontnotfounderror` is chosen becase this issue is inspired by it:
```TeX
\documentclass{article}
\usepackage{luatexbase}
\usepackage{fontspec}
\setmainfont{cmunrm.otf}
```
There will be a `\xetex_suppressfontnotfounderror:D` undefined error again :-).
> Change the flag of the early LaTeX2e format.

- l3kernel/l3doc.dtx
`\saved@indexname` is introduced by `doc` 2016/02/15 v2.1g.
> l3doc provides \saved@indexname.

- l3kernel/l3drivers.dtx
There were mismatched environments in the documentation of `l3kernel/l3drivers.dtx`.
> Fix documentation error

- l3build/l3build.lua
Usually, documentation is generated by simply typesetting a `dtx` file. In more complex cases, the file to typeset may first have to be unpacked from this `dtx`. The commits proposed herein allow for this scenario by searching for `typesetfiles` among the unpacked content, too.
> Also typeset unpacked files

- l3kernel/source3body.tex
Furthermore the mentioned `\xetex_if_engine:TF` is deprecated.
> Function definition did not match explanation

- l3build/l3build.dtx
- l3build/l3build.lua
This table essentially does for the *doc* command what the `checkfiles` do for *check*: Files specified in there are treated like `sourcefiles`, which means they are pulled into the unpacking process, only when typesetting the documentation.
Moving files needed in the documentation from the `sourcefiles` to this variable keeps them from interfering with other processes and speeds them up.
> establish a typesetsourcefiles variable

- l3kernel/l3tl.dtx
By deleting the requirement that it should have character code 32.
> Corrected the definition of 'explicit space'

- l3kernel/expl3.dtx
- l3kernel/l3basics.dtx
- l3kernel/l3box.dtx
- l3kernel/l3drivers.dtx
- l3kernel/l3expan.dtx
- l3kernel/l3file.dtx
- l3kernel/l3fp-aux.dtx
- l3kernel/l3int.dtx
- l3kernel/l3msg.dtx
- l3kernel/l3prg.dtx
- l3kernel/l3skip.dtx
- l3kernel/l3str.dtx
- l3kernel/l3tl.dtx
Using the information which can be corrected from `<arg-spec>` of each functions, we can detect the form of the arguments (e.g. number of arguments, `\Arg` or `\meta`). Based on this concept, I wrote a simple Python3 script to analyze all `syntax` environments in `interface3.pdf`:
- <https://gist.github.com/wtsnjp/c5eac5ce080716818f00238443024362>
Then I fixed every mistakes in the document which I found with the script.
> Fix documentations

- l3kernel/l3drivers.dtx
`\c_space_tl` is passed to a function (`\@@_color_select:n`) which does not
expand its argument, and results in `xxx "color push \c_space_tl Black"`
with the dvipdfmx backend. `\@@_color_select:n` already inserts appropriate
~, so `\c_space_tl` is unnecessary anyway.
To reproduce this bug, build source3 with the (x)dvipdfmx backend using
lualatex/xelatex. (x)dvipdfmx should complain about the incorrect color
specials.
> l3drivers: remove extra \c_space_tl

- l3kernel/l3coffins.dtx
If an expandable token is passed as a pole, then the expanded version
would be printed rather than the exact token list that was searched.
---
I only ran into this particular case of the bug. It could well be that there are other similar cases and that it makes more sense to variants instead of using `\exp_not:n`.
> Prevent expansion of pole in error message

- l3kernel/l3luatex.dtx
It was broken just because of a simple typo: `\@@_shiphout:n` -> `\@@_shipout:n`
> Fix \lua_shipout_e:n

- l3kernel/l3keys.dtx
Found this while migrating from `pgfkeys`.
> Fix typos in l3keys documentation [ci skip]

- l3kernel/l3coffins.dtx
- l3kernel/l3doc.dtx
- l3kernel/l3file.dtx
- l3kernel/l3fp.dtx
Apologize for using "[l3doc]" prefix in the commit messages. I have misunderstood the meaning of that tag at that time.
> Doc typo [ci skip]

- l3kernel/source3body.tex
Regarding the 'f' argument specifier, mention the fact that if the first non-expandable token found during the expansion is a 〈space token〉, it is gobbled.
expl3.pdf says this, but not the _Naming functions and variables_ section in interface3.pdf. This commit adds the missing precision in source3body.tex.
Note: I used the \meta{space token} notation to mean the same thing as in the TeXbook, I hope this is okay for LaTeX3 docs.
Thanks!
> Fix documentation of 'f' specifier in l3kernel/source3body.tex

- l3kernel/l3drivers-pdf.dtx
\tex_pdffeedback:D annot does not exists. Use lastannot instead.
> Fix typo in LuaTeX \driver_pdf_annotation_last:

- l3kernel/l3doc.dtx
Changed `\@@_xmacro_code:n` and `\@@_xmacro_code:w` to loop through the `<@@=` in the `macrocode` block allowing arbitrarily many changes of module name.
> Allow multiple <@@= in one macrocode (fixes #595)

- l3kernel/l3debug.dtx
- l3kernel/testfiles/m3flag001.tlg
- l3kernel/testfiles/m3int001.luatex.tlg
- l3kernel/testfiles/m3int001.tlg
- l3kernel/testfiles/m3int001.uptex.tlg
- l3kernel/testfiles/m3int001.xetex.tlg
Changed the patching scheme to create a wrapper around the function instead of patching its code directly, so functions without arguments can be patched as well. 2 test files changed as well: `m3int001` (all four versions) because TeX reports the error in the inner `\__debug_int_set:Nn` function and `m3flag001` because the error message changed to expandable.
> Fixed debug patching

- l3packages/xparse/xparse.dtx
> xparse: fix typo [ci skip]

- l3kernel/l3doc.dtx
Some indexing fixes after Stone-Zeng's comments in #450. Namely:
1) Replace <@@=...> by <@@@@=...> in comments (bug introduced with #596);
2) Fixed `\@for\@tempa:=` (: is a letter here): replaced by `\clist_map_inline:Nn`;
3) Removed indexing of pseudo commands (`\meta{name}:\meta{signature}`);
4) `\>` would become `\!\efill` and `|` and `=` would fail to index.
> Some indexing fixes to the l3doc doc (see #450)

- l3kernel/l3doc.dtx
Don't use `\file_input:nT`, which has been removed in commit ecd4174da983941f30d3231e44b526c079d674ec. Use `\file_input:n` instead.
> l3doc.cls: fix bug when trying to read l3doc.cfg

- l3kernel/doc/l3prefixes.csv
Register the `extblx` prefix for `expl3` code of the `biblatex-ext` bundle.
> Register biblatex-ext prefix (extblx)

- l3kernel/CHANGELOG.md
- l3kernel/expl3.dtx
- l3kernel/l3deprecation.dtx
- l3kernel/testfiles/m3deprecation004.lvt
- l3kernel/testfiles/m3deprecation004.tlg
I'm not entirely sure about this one...
The `undo-recent-deprecations` seemed to have no effect: when doing
`\sys_load_deprecation:` at the end the kernel, `l3deprecation.def` would
be loaded without `undo-recent-deprecations` and then the boolean
`\g__sys_deprecation_bool` would be set to true, thus it would not load
the deprecation code again if `undo-recent-deprecations` was used (that
is, if my analysis it correct).
I think this commit should fix that...
Also, I'm not sure how do we test this type of thing. The test I added uses
`\msg_term:n`, but in 6 months this will not work anymore...
> Fix `undo-recent-deprecations` to reload l3deprecation.def

- l3kernel/l3tl.dtx
Hello,
AFAICT, `\tl_range:nnn` accepts integer expressions for its second and third arguments. This is because of:
```latex
\cs_new:Npn \@@_range:nnnNn #1#2#3
{
\exp_args:Nff \@@_range:nnNn
{
\exp_args:Nf \@@_range_normalize:nn
{ \int_eval:n { #2 - 1 } } {#1}
}
{
\exp_args:Nf \@@_range_normalize:nn
{ \int_eval:n {#3} } {#1}
}
}
```
Thanks!
> \tl_range:nnn accepts integer expressions

- l3kernel/l3fp.dtx
- Misnamed arguments in `fp_compare_p:n` and `fp_compare_p:nTF`
- Misspelling in rounding section
> Fix some typos in l3fp docs

- l3kernel/l3keys.dtx
- l3kernel/testfiles/m3keyval001.luatex.tlg
- l3kernel/testfiles/m3keyval001.tlg
- l3kernel/testfiles/m3keyval002.luatex.tlg
- l3kernel/testfiles/m3keyval002.lvt
- l3kernel/testfiles/m3keyval002.tlg
This pull request ports the changes made to `expkv` in v1.0 (modulo some corrections) to `l3keys`'s `\keyval_parse:NNn`. As a result this is 25%-35% faster than the current implementation.
This merge also fixes some minor (up to now) undetected bugs introduced with https://github.com/latex3/latex3/pull/678 and some inconsistent behaviour which was already observable with the version prior to that PR.
All these behaviour changes are related to the behaviour of empty or blank key names. This version will throw a `blank-key-name` error on all of the following inputs (except for the very first key-value list element which is completely blank, this case is still silently ignored as it should be):
```tex
\keyval_parse:NNn \use_none:n \use_none:nn
{
, {}
, { ~ }
, = value
, {} = value
, { ~ } = …
```
> New splitting implemented

- l3backend/l3backend-pdf.dtx
Example document why this is needed:
~~~~
\RequirePackage{l3pdf}
\ExplSyntaxOn
\pdf_uncompress:
\ExplSyntaxOff
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\pdf_object_new:nn{ar1}{dict}
\pdf_object_new:nn{ar2}{dict}
\pdf_object_write:nn {ar1}{/A/B}
\pdf_object_write:nn {ar2}{/B/C}
\pdf_object_new:nn{blub}{array}
\pdf_object_write:nx {blub}{\pdf_object_ref:n {ar1} \pdf_object_ref:n {ar2}}
\ExplSyntaxOff
abc
\end{document}
~~~~
without the fix this creates (see the various null entries):
~~~~
4 0 obj
<</A/B>>endobj
5 0 obj
<</B/C>>endobj
6 0 obj
[null
null
null
null
5 0 R ]endobj
~~~~
with the fix the expected:
~~~~
4 0 obj
<</A/B>>endobj
5 0 obj
<</B/C>>endobj
6 0 obj
[ 4 0 R 
5 0 R ]endobj
~~~~
> correct array writing in dvips mode, index missing

- contrib/testfiles/ctex002.luatex.tlg
- l3kernel/expl3.dtx
- l3kernel/testfiles/m3expl007.lvt
- l3kernel/testfiles/m3expl008.luatex.tlg
- l3kernel/testfiles/m3expl008.lvt
- l3kernel/testfiles/m3expl008.tlg
This PR contains some internal changes to `expl3.dtx` to allow `expl3` to be loaded earlier in the LaTeX2e kernel.  The complement branch for this one is at [ `latex2e/earlier-expl3`](https://github.com/latex3/latex2e/tree/earlier-expl3).  The changes in this pull request are, however, independent of the ones in the aforementioned branch, so this can be safely updated before LaTeX2e.
> Changes to expl3 to allow loading earlier in LaTeX2e

- l3kernel/doc/l3prefixes.csv
As discussed via email I'd like to register this prefix to collect multiple corporate design templates which won't interact with each other. 
Because it's not directly a package i called the module ptxcd but was not sure how use the url fields. I can offer to add a webpage where I collect all templates, which use this prefix. 
Thanks for your work.
> Register prefix (ptxcd)

- l3kernel/doc/l3prefixes.csv
I would like to register the `pgf` prefix for future usage and in anticipation of someone else attempting to register it.  It is not actively used yet, but eventually we hope to be able to migrate PDF resource management to `pdfresources` (at least for LaTeX) which will make this necessary.
> Register prefix (pgf)

- l3packages/xparse/xparse.dtx
- l3packages/xtemplate/xtemplate.dtx
- In `xtemplate.dtx`, replace mis-spelled `\cs{EvaluteNow}` to `\cs{EvaluateNow}`.
- In `xparse.dtx`, avoid short verb `|...|` in the argument of `\texttt`.
The second typo, introduced in https://github.com/latex3/latex3/commit/dd0062fa65d32f4974691f51d773c6949484b197, causes following error when running `lualatex xparse.dtx` to get the doc of `xparse` with documented implementation:
```
! LaTeX Error: \verb illegal in command argument.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
...
l.2243 %   of~\dots~has an extra~|}
|}.
```
> Fix two typos in doc [ci skip]

- l3kernel/l3keys.dtx
- l3kernel/testfiles/m3keys001.lvt
- l3kernel/testfiles/m3keys001.tlg
- l3kernel/testfiles/m3keys005.lvt
- l3kernel/testfiles/m3keys005.tlg
- l3kernel/testfiles/m3quark001.tlg
This pull request changes the definition of `\__keys_trim_spaces:n` to not use `\tl_trim_spaces:n`, but instead directly remove the spaces around slashes in its loop. As a result `\keys_set:nn{test}{key=val}` with `\keys_define:nn{test}{key .tl_set:N = \l_test_key_tl}` gets more than 10% faster according to my benchmarks.
Also a faster `\__keys_parent:o` version is added (and the unused `:n` type dropped).
The function `\__keys_find_key_module:NNw` got replaced by `\__keys_find_key_module:wNN`.
The function `\__keys_property_find:n` also got faster and two (to my knowledge) unreported bugs got fixed. If a key path contained at least one period (additionally to the one starting the property), an empty `\l__keys_module_str` wasn't handled correctly, and a trailing space wasn't stripped from …
> Faster keys

- l3kernel/doc/l3prefixes.csv
Starting from platex 2020-09-30, we decided to use "platex".
> Register prefix (platex)

- l3kernel/doc/l3prefixes.csv
It's not a big package, but since this is to avoid duplicates, you get a registration. I hope you are fine with this, otherwise I can also stick to L2 Syntax for the internal macros.
> Register prefix (prelim for prelim2e)

- .travis.yml
Used official linter from travis 1.10.0 (https://github.com/travis-ci/travis.rb#lint) to find the last two issues, `skip_cleanup: true` is now default as per https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release#cleaning-up-the-git-working-directory. `on_start` isn't present for email https://docs.travis-ci.com/user/notifications/#configuring-email-notifications. Explicitly setting the `os` and `dist` settings, as that's general good practice.
> [.travis.yml] Set `os`, `dist` and remove `on_start` and `skip_cleanup`

- l3backend/l3backend-pdf.dtx
This corrects the link last code for newer xdvipdfmx. Beside others one has to use    \@@_backend:x
to expand the int, but I'm not sure if this means that one should surround the `#1` with an \exp_not-
> linklast for xdvipdfmx: correct int name, increase, avoid obj name clash

- l3kernel/CHANGELOG.md
- l3kernel/l3keys.dtx
- l3kernel/testfiles/m3keyval003.luatex.tlg
- l3kernel/testfiles/m3keyval003.lvt
- l3kernel/testfiles/m3keyval003.tlg
In https://tex.stackexchange.com/questions/573812/ Ulrich asked why `\keyval_parse:NNn` is restricted to N-type arguments, so I've implemented the n-type arguments.
I've also ported a few minor performance tweaks from `expkv`. Netting a better performance in total (but the performance would be better without the n-type support, I'd estimate 3% to 5%).
------
Benchmarking results with `\keyval_parse:NNn \use_none:n \use_none:nn` and the following token list:
<code>,<sub>12</sub>,<sub>12</sub>key=<sub>13</sub>val,<sub>13</sub>key=<sub>12</sub>val,<sub>12</sub>key</code>
I've replicated that token list 1, 10, 100, and 1000 times. In the case of 1 the first comma is missing. The ratios shown below are the multiple of the run times needed; so in the case `\mykeyval_parse:nnn / …
> allow n-type arguments for keyval_parse

- l3backend/l3backend-pdf.dtx
pdftex and luatex allows to use fitr without rule spec, they then fill the coordinates by using the surrounding box. 
This can be useful sometimes, so this adds it as option to \@@_backend_destination:nn.   For dvipdfmx and dvips /Fit is used as fallback.
> add fitr support to \@@_backend_destination:nn

- l3kernel/l3file.dtx
- l3kernel/l3intarray.dtx
Hi, just a couple of typographical changes `TeX(live|Live)` => `TeX Live` (I was uncomfortable seeing it in lowercase and all together).
PD: By default my editor removes the spaces at the end of the line :)
Saludos
> Fix typo TeX(live|Live) => TeX Live

- l3backend/CHANGELOG.md
- l3backend/l3backend-pdf.dtx
- l3kernel/CHANGELOG.md
- l3kernel/l3pdf.dtx
This sets the pdf version value for dvips as discussed. the test files don't catch this change, as we don't test dvips ...
> set pdf version values also with dvips

- l3kernel/l3doc.dtx
wspr had already done essentially all the work fixing this, but the regex
wasn't quite right: it didn't correctly omit hyphenation after a backslash
when it was followed by two (or more) underscores.
> Avoid hyphenation in the first run of _ in l3doc's \cs (fixes #479)

- l3kernel/CHANGELOG.md
- l3kernel/l3regex.dtx
- l3kernel/testfiles/m3regex005.luatex.tlg
- l3kernel/testfiles/m3regex005.lvt
- l3kernel/testfiles/m3regex005.tlg
- l3kernel/testfiles/m3regex005.xetex.tlg
The code now uses the current values of `\catcode` to decide what token to produce.  E.g.,
\regex_replace_all:nnN { .* } { $a^{b+1}$ } \l_tmpa_tl
\tl_analysis_show:N \l_tmpa_tl
will now show the catcodes one would see upon rescanning `$a^{b+1}$` with the current catcodes.  This is a breaking change, so I'd like some opinions.  No need to look at the code, I think, but I'd like to know if the doc is clear.
> Change catcode produced by default by l3regex replacement (fixes #621)

- l3kernel/CHANGELOG.md
- l3kernel/l3file.dtx
When a filename without extension is passed to \file_full_name:n, it accesses the file four times using \pdffilesize. Here this is reduced to two times (on different names, so not really avoidable) by preserving the results and reusing them.
> Dont't duplicate \pdffilesize in \file_full_name:n

- l3kernel/CHANGELOG.md
- l3kernel/l3candidates.dtx
- l3kernel/testfiles/m3seq005.lvt
- l3kernel/testfiles/m3seq005.tlg
- `\seq_put_item:Nnn` places an item at a certain position in the sequence (removing the item that was previously there), and errors if the position is out of bounds (zero or larger [in absolute value] than the number of items)
- `\seq_put_item:NnnTF` does not error, it returns false if the position is out of bounds
- `\seq_pop_item:NnN(TF)` does not error: it removes the item if possible and stores it in `#3`, and if the position is out of bounds it does not change the sequence and it stores `\q_no_value` in `#3`
Thoughts about the interface are welcome.  Especially what `\seq_put_item:Nnn` should do when the position is out of bounds.  Two useful comparisons: the `\seq_item:Nn` function simply expands to nothing if the position is out of bounds, and the `\prop_put:Nnn` function of …
> Changing items at specific positions of a sequence (fixes #844)

- l3kernel/CHANGELOG.md
- l3kernel/l3clist.dtx
- l3kernel/l3fp-assign.dtx
- l3kernel/l3fp.dtx
- l3kernel/l3kernel-functions.dtx
- l3kernel/l3msg.dtx
- l3kernel/l3prg.dtx
- l3kernel/l3prop.dtx
- l3kernel/l3regex.dtx
- l3kernel/l3seq.dtx
- l3kernel/l3str.dtx
- l3kernel/l3tl.dtx
- l3kernel/testfiles/m3show003.luatex.tlg
- l3kernel/testfiles/m3show003.lvt
- l3kernel/testfiles/m3show003.tlg
This slows down `show` commands somewhat, especially `\regex_show:N`/`\regex_log:N`, but at most by a factor of 2 or so, so I figured this is ok.
I opted not to fix the fact that \int_show:N, \dim_show:N etc are equivalent (hence accept the wrong type of data) because this is messy to check.
> Validate internal structure when showing complex datatypes (fixes #884)

- l3kernel/CHANGELOG.md
- l3kernel/l3basics.dtx
- l3kernel/l3coffins.dtx
- l3kernel/l3color.dtx
- l3kernel/l3file.dtx
- l3kernel/l3msg.dtx
- l3kernel/l3tl-analysis.dtx
- l3kernel/testfiles/m3coffins001.luatex.tlg
- l3kernel/testfiles/m3coffins001.lvt
- l3kernel/testfiles/m3coffins001.ptex.tlg
- l3kernel/testfiles/m3coffins001.tlg
- l3kernel/testfiles/m3coffins001.uptex.tlg
- l3kernel/testfiles/m3coffins001.xetex.tlg
- l3kernel/testfiles/m3color002.lvt
- l3kernel/testfiles/m3color002.tlg
- l3kernel/testfiles/m3ior002.lvt
- l3kernel/testfiles/m3ior002.tlg
- l3kernel/testfiles/m3iow001.luatex.tlg
- l3kernel/testfiles/m3iow001.lvt
- l3kernel/testfiles/m3iow001.ptex.tlg
- l3kernel/testfiles/m3iow001.tlg
- l3kernel/testfiles/m3iow001.uptex.tlg
- l3kernel/testfiles/m3iow001.xetex.tlg
- l3kernel/testfiles/m3show003.lvt
- l3kernel/testfiles/m3show003.tlg
- l3kernel/testfiles/m3tl-analysis001.luatex.tlg
- l3kernel/testfiles/m3tl-analysis001.lvt
- l3kernel/testfiles/m3tl-analysis001.tlg
- l3kernel/testfiles/m3tl-analysis001.xetex.tlg
This adds `\coffin_show:Nnn`, `\coffin_show:N`, `\coffin_log:Nnn`, `\coffin_log:N`, `\color_log:n`, `\group_show_list:`, `\group_log_list:`, `\ior_show:N`, `\ior_log:N`, `\iow_show:N`, `\iow_log:N`, `\tl_log_analysis:N`, `\tl_log_analysis:n`.
> Add missing show and log commands (fixes #241)

- l3kernel/l3tl.dtx
Just a minor typo in a control sequence name.
> Fix small typo

- l3kernel/doc/l3prefixes.csv
I would like to register the `markdown` prefix for [the Markdown package](https://ctan.org/pkg/markdown) as a part of modernization efforts (https://github.com/Witiko/markdown/issues/96, https://github.com/Witiko/markdown/pull/77) that include partial rewrite in expl3.
> Register prefix markdown

- l3kernel/CHANGELOG.md
- l3kernel/l3box.dtx
The macro `\box_gresize_to_ht_plus_dp:Nn` currently does not a global but a local assignment. It's as small as a typo but I'd really to love to get this one fixed. 
I was not sure if I also should touch the “updated” date for the macros. Please let me know If should have adjusted that one was well or if this is up to you.
Thanks a lot.
> fix box_gresize_to_ht_plus_dp to be global

- l3kernel/l3str.dtx
These are strings but token lists
> Seems to be typo

- l3kernel/l3keys.dtx
- l3kernel/l3msg.dtx
- l3kernel/l3prop.dtx
- l3kernel/testfiles/m3color003.ptex.tlg
- l3kernel/testfiles/m3color003.tlg
- l3kernel/testfiles/m3color003.uptex.tlg
- l3kernel/testfiles/m3color003.xetex.tlg
- l3kernel/testfiles/m3prop005.tlg
This PR will change the `_from_keyval:Nn` functions of the `l3prop` module to use `\keyval_parse:nnn` instead of the more limited implementation in the `l3prop` module. This will result in the property list functions supporting active equals and commas. Since usage on stackexchange indicates that the property list functions are also used to parse user input (see e.g. [here](https://tex.stackexchange.com/a/418021/117050) and [here](https://tex.stackexchange.com/a/589159/117050)) and not only as an interface at the programming level this seems like a good idea.
As a bonus, this will result in a speed increase of roughly 30 %.
I've made a minor change to an internal of `l3keys` (the macro which would throw an error on blank key names) to allow those as long as …
> l3prop: use \keyval_parse:nnn for ..._from_keyval:Nn

- l3kernel/l3fp-expo.dtx
- l3kernel/l3fp-parse.dtx
- l3kernel/l3str.dtx
The `\pdfstrcmp` primitive (and equivalent implementations, including the current Lua code used by `expl3` in LuaTeX) doesn't return its result as a count register or similar, but as a tokens of category 12. It is therefore faster to check whether the result is equal to `0` by using the `\if` primitive instead of `\ifnum` (my benchmarks indicate 10% speed difference for the check in pdfTeX).
This changes those usages of `\pdfstrcmp` in which the result is only tested to be equal to zero to use `\if`.
> Speed up string comparison by using \if

- l3kernel/l3keys.dtx
- l3kernel/l3prop.dtx
As suggested by @PhelypeOleinik in #1012 this moves the newly introduced `\l__keyval_allow_blank_keys_bool` to the `kernel` namespace since it's used across multiple modules.
> move keyval_allow_blank_keys_bool to kernel namespace

- l3kernel/CHANGELOG.md
- l3kernel/l3clist.dtx
- l3kernel/l3keys.dtx
- l3kernel/testfiles/m3keys007.lvt
- l3kernel/testfiles/m3keys007.tlg
This PR covers the `expl3` part of the plans for option handling. All internal l3keys work is covered here at present.
> Add support for validity scope for keys

- l3kernel/CHANGELOG.md
- l3kernel/l3regex.dtx
- l3kernel/testfiles/m3intarray001.luatex.tlg
- l3kernel/testfiles/m3intarray001.tlg
- l3kernel/testfiles/m3regex012.lvt
- l3kernel/testfiles/m3regex012.tlg
This implements `\regex_case_match:nn(TF)`, `\regex_case_replace_once:nN(TF)`, `\regex_case_replace_all:nN(TF)` which can do different code/replacements depending on which of several regex match.  See the documentation in l3regex and issue #433 for details.
I don't expect the code to be reviewed in detail as it's pretty complicated and connects to many parts of l3regex, but if someone else can test beyond the existing test files that would be great.
> Tools to match/replace multiple regex concurrently (fixes #433)

- l3backend/CHANGELOG.md
- l3backend/l3backend-color.dtx
- l3experimental/l3draw/testfiles/m3draw003.xetex.tlg
- l3experimental/l3draw/testfiles/m3draw004.xetex.tlg
- l3experimental/l3draw/testfiles/m3draw005.xetex.tlg
- l3experimental/l3draw/testfiles/m3draw006.xetex.tlg
- l3experimental/l3draw/testfiles/m3draw007.xetex.tlg
- l3experimental/xcoffins/testfiles/xcoffins003.xetex.tlg
- l3kernel/testfiles/d3dvipdfmx.luatex.tlg
- l3kernel/testfiles/d3dvipdfmx.tlg
- l3kernel/testfiles/d3dvipdfmx.xetex.tlg
- l3kernel/testfiles/d3dvips.xetex.tlg
- l3kernel/testfiles/d3pdfmode.xetex.tlg
- l3kernel/testfiles/d3xetex.xetex.tlg
- l3kernel/testfiles/m3box004.xetex.tlg
- l3kernel/testfiles/m3coffins001.xetex.tlg
Compared to the proposal I posted in #1042, `\c_space_tl` is used right after `\int_use:N \g_xxx_int`, instead of `~`.
The corresponding code lines are introduced in https://github.com/latex3/latex3/commit/3e1892e810c6f47c4b7f6de87aeda7b64db0a257, and the `.tlg` lines in https://github.com/latex3/latex3/commit/87b591a9e2d5f9d983660ed4927b5045cef31756 (mostly as I didn't carefully check it).
Is a changelog entry needed?
Fixes #1042
> Use content of `\g__color_backend_stack_int`

- l3kernel/doc/l3prefixes.csv
I'm converting my `lua-widow-control` package to use `expl3` at gucci-on-fleek/lua-widow-control#20, so I would like to register the module prefix `lwc`. I'm seeing a few other PRs doing the same thing in this repository, so I _think_ that I did it correctly.
Thanks!
> Register prefix `lwc`

- l3kernel/CHANGELOG.md
- l3kernel/l3luatex.dtx
- l3kernel/l3msg.dtx
- l3kernel/l3names.dtx
- l3kernel/l3token.dtx
- l3kernel/testfiles/m3char001.luatex.tlg
- l3kernel/testfiles/m3char001.lvt
- l3kernel/testfiles/m3char001.ptex.tlg
- l3kernel/testfiles/m3char001.tlg
- l3kernel/testfiles/m3char001.uptex.tlg
- l3kernel/testfiles/m3char001.xetex.tlg
Pretty much what the title says... Add LuaTeX support by injecting token userdata instead of relying on `cprint` to avoid changing the charcode to 32, for other engines it just removes the check.
> Support space tokens in \char_generate:nn

- l3kernel/CHANGELOG.md
- l3kernel/l3luatex.dtx
This PR adds a new command `\lua_load_module:n` to the `l3luatex` module as a replacement for `\lua_now:n { require "module" }`.
Right now, if you try and add a Lua module that doesn't exist, you get a fairly unpleasant error message.
```tex
\ExplSyntaxOn
\lua_now:n { require "does-not-exist" }
\ExplSyntaxOff
```
```log
[\directlua]:1: module 'does-not-exist' not found:
no field package.preload['does-not-exist']
[kpse lua searcher] file not found: 'does-not-exist'
stack traceback:
[C]: in function 'require'
[\directlua]:1: in main chunk.
\lua_now:e #1->\__lua_now:n {#1}
l.13     \lua_now:n { require "does-not-exist" }
The lua interpreter ran into a problem, so the
remainder of this lua chunk will be ignored.
! Emergency stop.
```
The problem here is that the file `does-not-exist.lua` …
> Add new command `\lua_load_module:n`

- l3kernel/doc/l3prefixes.csv
I would like to register the luabridge prefix for [the lt3luabridge package](https://github.com/Witiko/lt3luabridge).
> Register prefix lt3luabridge

- l3kernel/expl3.dtx
The generic loader is named `expl3-generic.tex`, not `expl3.tex`.
See commit 6edc6754d4f4b1ada1f919974ac7ee9deea1108c
> docs: fix a typo for name of generic load

- l3kernel/l3file.dtx
In #1114, we used `\c_sys_engine_format_str` to detect the ConTeXt format in l3file. However, [further discussion with ConTeXt developers][1] indicates that the existence of the `\contextversion` command is a more robust test. This pull request replaces the four tests in l3file with the more robust test.
[1]: https://mailman.ntg.nl/pipermail/dev-context/2022/003916.html
> Make ConTeXt detection in l3file more robust

- l3kernel/l3keys.dtx
The current documentation writes `\keys define:nn` instead of `\keys_define:nn`.
> docs: fix a typo in l3keys [ci skip]

- l3kernel/l3candidates.dtx
> Fix `cs_to_str:N` misspelled as `cs_to_sr:N`

- .github/workflows/deploy.yaml
- .github/workflows/main.yaml
- Update GH Actions to eliminate `Node.js 12 actions are deprecated.` warnings
- Use [context `github.ref_name`][github.ref_name] to replace action `frabert/replace-string-action`
PS: Would you like to have a [dependabot]? See use case in [texstudio] and [pgf].
[github.ref_name]: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
[dependabot]: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
[texstudio]: https://github.com/texstudio-org/texstudio/blob/master/.github/dependabot.yml
[pgf]: https://github.com/pgf-tikz/pgf/blob/master/.github/dependabot.yml
PS 2: Warnings thrown in latest Actions runs
<details>
<summary> https://github.com/latex3/latex3/actions/runs/4076719889 </summary>
> …
> Update GH Actions

- l3kernel/doc/interface3.tex
- l3kernel/l3box.dtx
- l3kernel/l3candidates.dtx
- l3kernel/l3cctab.dtx
- l3kernel/l3clist.dtx
- l3kernel/l3coffins.dtx
- l3kernel/l3file.dtx
- l3kernel/l3fp-parse.dtx
- l3kernel/l3fp-round.dtx
- l3kernel/l3fp.dtx
- l3kernel/l3int.dtx
- l3kernel/l3intarray.dtx
- l3kernel/l3skip.dtx
- l3kernel/l3sys.dtx
- l3kernel/l3token.dtx
fpexpr  and floating point expression -> fp expr
ditto for intexpr dimexpr skipexpr and muskipexpr
not sure which is better short or long.
There is also an issue with l3doc which I temp corrected in interface3 to see how it comes out. \meta does italic but \Arg uses meta inside \texttt so the two differ next to each other, not sure how this is best handled \Arg to use normalfont itshape or \meta us tt it as I did here?
> trial update for #968

- l3kernel/l3expan.dtx
Changes non-existent `\exp_arg:N` to `\exp_args:N<variant>`, as already mentioned in `l3expan.dtx`, line 156 below
https://github.com/latex3/latex3/blob/c250fd483f8806b5986a0dcc838250c452ca5ddd/l3kernel/l3expan.dtx#L147-L157
Fixes #1166
> Fix docs typo

- l3backend/CHANGELOG.md
- l3backend/build.lua
- l3backend/l3backend-color.dtx
- l3backend/l3backend-opacity.dtx
- l3backend/l3backend.ins
- l3kernel/CHANGELOG.md
- l3kernel/l3names.dtx
Integrate l3color and l3opacity with luaotfload to allow both systems to set colors and transparency without interfering with one another.
> Integrating l3color/l3opacity and luaotfload

- l3kernel/CHANGELOG.md
- l3kernel/l3candidates.dtx
Fixes #1186
Need a new test file, perhaps in suite `testfiles-backend`?
> Fix minor version in `\c_sys_engine_version_str` for pdfTeX and LuaTeX

- l3experimental/l3draw/l3draw.dtx
Currently a line cap function `\draw_cap_butt:` is used as the representative  for line join functions (`\draw_join_xxx:n`). This PR corrects it to `\draw_join_miter:`, representing the initial line join state.
> Fix doc typo for `l3draw`

- l3backend/CHANGELOG.md
- l3backend/l3backend-graphics.dtx
- l3experimental/CHANGELOG.md
- l3experimental/l3graphics/l3graphics.dtx
Most of the change here is trivial. Note the adjustment needed for XeTeX
as \XeTeXpdffile does not support adding attributes.
> Add "pdf-attr" key to l3graphics

- l3kernel/CHANGELOG.md
- l3kernel/l3keys.dtx
- l3kernel/testfiles/m3keys001.lvt
- l3kernel/testfiles/m3keys001.tlg
Similar to ed957e9 (Set \l_keys_key_str in .initial:n(fixes #1013), 2023-05-22).
@blefloch wrote
> When processing `.initial:n`, only `\l_keys_path_str` is set, and not `\l_keys_key_str` (perhaps others are also missing?).
in #1013 hence I think this PR is loosely related to that issue.
> Set `\l_keys_value_tl` in `.initial:n`

- l3kernel/CHANGELOG.md
introduced in 41c4d369c7560296d484c468d42b3dc0ce4734b8
Pointed out by @mbertucci47 in https://github.com/latex3/latex3/commit/41c4d369c7560296d484c468d42b3dc0ce4734b8#r120959892.
> Fix typo in CHANGELOG

- l3kernel/CHANGELOG.md
- l3kernel/l3sys.dtx
They were added by commit 1867e95 (Move timer to sys, 2020-10-05), as part of PR #859 which was merged on 2021-05-12.
The added date is set to 2021-05-12, the merged date, because the commit date (2020-10-05) and current added date of `\sys_timer:` (2020-09-24) are both quite prior to merged date of such commit.
> Add documentation for `\sys_if_timer_exsit_p:` and `\sys_if_timer_exsit:(TF)`

- l3kernel/l3keys.dtx
- l3kernel/l3tl.dtx
This commit fixes several missing commas in the documentation.
Before:
After:
> Fix typos of missing commas

- l3kernel/doc/l3prefixes.csv
I'd like to register the “slcd” prefix used for my `se2thesis` bundle on CTAN.
> Register “slcd” prefix

- l3experimental/l3str/l3str-format.dtx
- l3kernel/l3fp.dtx
- l3trial/l3str-format-new/l3str-format-new.dtx
About `\begin{quote}\let\obeyedline=\newline\obeylines^^A`
- Compared to inserting `\\` per line, would this way be too tricky?
- `verbatim` env is another option, but auto indexing is disabled.
- By default `\obeyedline` uses `\par`, which will make larger visual "line spacing". Hence I redefined it (locally) to use `\newline`.
About `\subsection` -> `\section`, I'm also considering changing their titles or even restructuring them. Maybe in a later PR.
- It's a bit hard to infer from only the title "Symbolic expressions" to know that expl3 functions about fp expr variables are documented under it.
- And since "function" is also used to represent an expl3 function, the second title "User-defined functions" is more or less ambiguous.
> Fix doc typos mainly for fp var and funcs

- .github/workflows/deploy.yaml
- .github/workflows/main.yaml
Currently CI (workflow defined in `main.yaml`) was not triggered by pushing commits to a branch having `/` in its name. This PR fixes it by relaxing the glob pattern.
> - `*`: Matches zero or more characters, but does not match the `/` character. For example, `Octo*` matches `Octocat`.
> - `**`: Matches zero or more of any character.
See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet.
> Allow all branches to trigger CI

- l3kernel/CHANGELOG.md
- l3kernel/expl3.dtx
As `\ExplLoaderFileDate` is already used to define `\IfExplAtLeastTF` in LaTeX2e (see https://github.com/latex3/latex2e/pull/1146), latex3 may want it and its expl3 alias `\c__kernel_expl_date_tl` documented somewhere.
Since they're both defined in loader file (`expl3.ltx`, `expl3.sty`, and `expl3-generic.tex`), I think `expl3.pdf` is more appropriate a place than `interface3.pdf` for their documentations. `interface3.pdf` never even mentions "loader(s)".
> Docu `\ExplLoaderFileDate` and `\c__kernel_expl_date_tl`

- l3kernel/CHANGELOG.md
- l3kernel/l3fp-functions.dtx
- l3kernel/l3fp-symbolic.dtx
- l3kernel/l3fp.dtx
- l3kernel/testfiles/m3fp-symbolic001.luatex.tlg
- l3kernel/testfiles/m3fp-symbolic001.lvt
- l3kernel/testfiles/m3fp-symbolic002.luatex.tlg
- l3kernel/testfiles/m3fp-symbolic002.lvt
- l3kernel/testfiles/m3fp-symbolic002.tlg
I'd like to recheck content of new `m3fp-symbolic002.tlg` file before merging.
> Fix `\fp_clear_function:n` acting globally, add tests, and a bit more

- l3kernel/CHANGELOG.md
- l3kernel/l3seq.dtx
This is the missing doc part of commit 69b7c6fd0 (Deprecate \seq_(g)set_map_x:NNn, 2023-10-26).
> Adapt doc for `\seq_set_map_e:NNn` and `\seq_gset_map_e:NNn`

- l3kernel/CHANGELOG.md
- l3kernel/l3fp-assign.dtx
- l3kernel/l3fp-functions.dtx
- l3kernel/l3fp-symbolic.dtx
- l3kernel/l3str.dtx
- l3kernel/testfiles/m3fp-symbolic001.luatex.tlg
- l3kernel/testfiles/m3fp-symbolic001.lvt
- l3kernel/testfiles/m3fp-symbolic001.tlg
- l3kernel/testfiles/m3fp-symbolic002.luatex.tlg
- l3kernel/testfiles/m3fp-symbolic002.lvt
- l3kernel/testfiles/m3fp-symbolic002.tlg
- l3kernel/testfiles/m3show003.tlg
> Support for `\fp_show:N` showing symbolic expressions

- l3kernel/l3basics.dtx
- l3kernel/l3clist.dtx
- l3kernel/l3expan.dtx
- l3kernel/l3keys.dtx
- l3kernel/l3prop.dtx
- l3kernel/l3seq.dtx
- l3kernel/l3tl.dtx
Change phrases "x-type and e-type expansion/argument" to "e-type and x-type ...".
Need a Changelog entry?
> Promote e-type expansion

- l3kernel/l3basics.dtx
- l3kernel/l3candidates.dtx
- l3kernel/l3clist.dtx
- l3kernel/l3deprecation.dtx
- l3kernel/l3doc.dtx
- l3kernel/l3file.dtx
- l3kernel/l3fp-aux.dtx
- l3kernel/l3keys.dtx
- l3kernel/l3msg.dtx
- l3kernel/l3prop.dtx
- l3kernel/l3regex.dtx
- l3kernel/l3seq.dtx
- l3kernel/l3str-convert.dtx
- l3kernel/l3tl-analysis.dtx
- l3kernel/l3tl.dtx
- l3kernel/l3token.dtx
I put changes that I'm not quite sure in the last commit ca91f4abd9151574758bc0ff87c35b8256080873, but after checking that there're almost no use of `x`-type expansion in `expl3-code.tex` unpacked from latest `main` branch, the x-to-e substitution seems to be right.
> Adapt doc and code comments to sync with x-to-e switch

- l3kernel/l3basics.dtx
- l3kernel/l3doc.dtx
- l3kernel/l3expan.dtx
- l3kernel/l3kernel-functions.dtx
- l3kernel/l3regex.dtx
- l3kernel/l3str.dtx
- l3kernel/l3tl-analysis.dtx
- l3kernel/l3tl-build.dtx
#1312 and #1313 dealt with `\texttt{x}` markups, and this PR dealt with `|x|` markups used mainly in `l3expan.dtx`.
Fortunately, there're no `"x"` usages, as `"` is another short verb characters supported in `function`-like environments by `l3doc`.
> Promote e-type expansion and sync docs with x-to-e switch, part 2

- l3kernel/CHANGELOG.md
- l3kernel/l3fp.dtx
It was added in commit fb3f38ff (First stage of installing new FPU: copy code and test files into l3kernel, 2012-05-09), along with other fp constants.
Reading l3fp implementation slowly, I found `\c_nan_fp` the only fp constant (in a group of five) that's not documented.
If user wants to process the expansion result of an `<fp expr>`, `\c_nan_fp` is needed in one case of `\str_case_e:nn(TF) {<fp expr>} {<string and code cases>}`.
> Document `\c_nan_fp`

- l3kernel/CHANGELOG.md
- l3kernel/l3int.dtx
- l3kernel/l3prg.dtx
- l3kernel/l3str.dtx
- l3trial/l3bigint/l3bigint.dtx
I noticed `\str_case_e:nnTF` while preparing PR #1309, then the need for its `e`-variant `\str_case_e:enTF` arose quickly, as in base function `#1` is expanded in each comparison, which would be slow if expanding `#1` is expansive. #1309 happened to only need to compare `#1` to single unexpandalble tokens, hence `\str_case:en(TF)` was enough. (`\str_case_e:en(TF)` would still be a little quicker, due to no `\exp_not:n`.)
The only copy of comment explaining case implementation is also added to `\str_case:nn(TF)` functions, picked from corresponding deprecated `\tl_case:Nn(TF)` functions. See commit https://github.com/latex3/latex3/commit/abae082902e6cd9f4694932e605b7660e3e88495 (Deprecate \tl_case:Nn(TF), 2023-05-23).
> Add variant `\str_case_e:en(TF)`

- l3backend/CHANGELOG.md
- l3backend/l3backend-color.dtx
Currently the `l3color` code interacting with luaotfload assumes that all colors are defined with l3color.
While this is a reasonable long-term goal, it is more practical to assume that some user might also use (x)color to define color names.
Therefore this changes the luaotfload hook to use the (x)color color definition if no color with the same name is defined in l3color.
> Improve l3color and (x)color coexistance in LuaLaTeX

- l3kernel/CHANGELOG.md
- l3kernel/l3prg.dtx
- l3kernel/testfiles/m3prg005.lvt
- l3kernel/testfiles/m3prg005.tlg
> Fix `\bool_to_str:n` and `\bool_to_str:N` returning letters

- l3kernel/l3deprecation.dtx
The entries for a few commands in l3deprecations.dtx have the wrong second argument to `\__kernel_patch_deprecation:nnNNpn`, repeating the deprecated command. This causes them to produce the wrong error when debugging, e.g.
```tex
! LaTeX Error: Use \bool_case_true:nT not \bool_case_true:nT
```
Full example:
```tex
\documentclass{article}
\ExplSyntaxOn
\debug_on:n { all }
\ExplSyntaxOff
\begin{document}
\ExplSyntaxOn
\bool_case_true:nT {}{}
\ExplSyntaxOff
\end{document}
```
> fix deprecated command entries

- l3kernel/l3deprecation.dtx
`\tl_case:NnF` and `\tl_case:cnF` are deprecated too, hence should be avoided in fallback definitions.
> Update fallback definitions for `\tl_case:Nnn` and `\tl_case:cnn`

- l3kernel/CHANGELOG.md
- l3kernel/build.lua
- l3kernel/l3debug.dtx
- l3kernel/l3str.dtx
- l3kernel/l3tl.dtx
Full list is `\str_(g)set:Nn`, `\str_const:Nn`, `\str_(g)put_left:Nn`, and `\str_(g)put_right:Nn`.
Their current implementations use a structure `\tl_<func>:Ne <str var> { \tl_to_str:n {<token list>}}`, which is slow. Since (the current implementation of) `\tl_to_str:n` needs only one expansion step, the `e`-type variants `\tl_<func>:Ne` can be replaced with `o`-type  variants. In addition since string won't expand further, the `\__kernel_exp_not:w` used in corresponding base functions `\tl_<func>:Nn` is superfluous.
This PR hand-tune these base functions by using structures similar to their `\tl_<func>:Nn` siblings.
If needed, their variants can be hand-tuned as well, just like corresponding `tl` variants. `\str_set:Ne` is one of commonly used variants I think.
I'll add tests on …
> Speed up string assignment functions like `\str_set:Nn`

- l3kernel/l3doc.dtx
`\l__codedoc_macro_internal_set_bool` and `\l__codedoc_macro_internal_bool` always have the same value, hence one of them can be dropped. Since `\l__codedoc_macro_internal_set_bool` was added more recently, by commit bf322508 (Treat macros as internal/not-internal on a individual basis, 2017-11-30), I decided to drop it.
Found when digging for #1345.
Need a Changelog entry?
> Drop repetitive `\l__codedoc_macro_internal_set_bool` and fix variant generations

- l3kernel/l3file.dtx
> In `l3kernel` repository,
> ```
> $ grep -rn '\\\(Arg\|meta\){filename}' **/*.dtx | wc -l
>        3
> $ grep -rn '\\\(Arg\|meta\){file name}' **/*.dtx | wc -l
>       47
> ```
> 
> _Originally posted by @muzimuzhi in https://github.com/latex3/l3build/issues/323#issuecomment-1846036749_
> Standarise "file name" in docs

- l3kernel/l3basics.dtx
- l3kernel/l3bitset.dtx
- l3kernel/l3seq.dtx
- l3kernel/l3str.dtx
Found when checking `l3build cmdcheck` output (run in `l3kernel` directory).
> Drop docs for removed internal functions

- l3kernel/l3bitset.dtx
This PR mainly corrects lost indentations found in several `l3bitset` function syntaxes. 
> From `texdoc l3bitset`, indents are missing in this and several more `syntax` envs.
> 
> <sub>_Originally posted by @muzimuzhi in https://github.com/latex3/latex3/pull/1341#discussion_r1394967095_</sub>
Sample comparisons
| Before | After |
|--------|--------|
| ![image](https://github.com/latex3/latex3/assets/6376638/f00b08d0-e6bd-4c91-be83-b518f72cee2f) | ![image](https://github.com/latex3/latex3/assets/6376638/bafcd950-f01b-428a-9d09-ef679abf181a) |
| ![image](https://github.com/latex3/latex3/assets/6376638/f51e9698-641f-43ea-a2ba-6ddb1613c760) | ![image](https://github.com/latex3/latex3/assets/6376638/55df48cd-6c0a-432f-88af-aadb25b32095) |
> Keep indents in l3bitset multi-line syntaxes, and more

- l3kernel/doc/l3prefixes.csv
This PR re-enables rendering of `l3prefixes.csv` on GitHub.
Before
https://github.com/latex3/latex3/blob/dc9f9616ccb3273dea833ea632fa6cf0a8f995cd/l3kernel/doc/l3prefixes.csv
After
https://github.com/muzimuzhi/latex3/blob/fix/csv-columns/l3kernel/doc/l3prefixes.csv
GitHub Docs https://docs.github.com/en/repositories/working-with-files/using-files/working-with-non-code-files#rendering-csv-and-tsv-data
> Add missing columns in prefix csv

- l3kernel/l3keys.dtx
`\__keys_trim_spaces:n` is now applied only once, after the last `.` is found.
This is a refactor (found in my almost lost `git stash`) that simplifies `\__keys_property_find:n` a little bit.
> Avoid trimming spaces twice on (raw) key names

- l3kernel/l3keys.dtx
This commit speeds up the `\@@_property_find:n` function of `l3keys` by roughly 20% - 30%.
> l3keys: Speed up property_find

- l3kernel/l3basics.dtx
The function `\use_i_ii:nn` shows up in the list of variants of `\use_i:n...`, even though it's documented separately.
> remove doubled documentation of use_i_ii

- l3kernel/CHANGELOG.md
- l3kernel/l3keys.dtx
- l3kernel/testfiles/m3keys001.lvt
- l3kernel/testfiles/m3keys001.tlg
This PR changes the unknown-handler invocation to support a default value for unknown keys. This would effectively close #67.
> Use `.default:n` value for unknown key

- .github/workflows/main.yaml
This PR removes irrelevant pdfs in `./build` directory and any sub-directory `testfiles*` from uploaded "Documentation" artifact. The specific removed pdfs are
```diff
--- a/old.txt
+++ b/new.txt
@@ -1,7 +1,4 @@
Documentation
-├── build
-│   └── doc
-│       └── l3graphics.pdf
├── l3backend
│   └── l3backend-code.pdf
├── l3experimental
@@ -11,13 +8,7 @@ Documentation
│   │   ├── l3draw-code.pdf
│   │   └── l3draw.pdf
│   ├── l3graphics
-│   │   ├── l3graphics.pdf
-│   │   └── testfiles
-│   │       └── support
-│   │           ├── example-image-a4-numbered.pdf
-│   │           ├── folder-a
-│   │           │   └── meow.pdf
-│   │           └── miau.pdf
+│   │   └── l3graphics.pdf
│   ├── l3opacity
│   │   └── l3opacity.pdf
│   ├── l3str
@@ -69,4 +60,4 @@ Documentation
├── xo-balance.pdf …
```
> Ignore irrelevant pdfs when uploading Documentation artifact

- l3kernel/doc/interface3.tex
- l3kernel/doc/source3.tex
Both `interface.pdf` and `source3.pdf` have more than doubled in thickness, since the last updates of page info, in 7a7a8b8d ([Big bang] Copy the documentation-related stuff into l3kernel, 2011-04-27) and 48e84cbb (Fix a typo in l3tl, 2012-09-05), respectively.
> Update number of pages in interface3 and source3

- l3kernel/l3doc.dtx
For the typo,
- before
> `kernel`
> Determines whether `l3doc` treats `\__kernel_` commands and `\(cgl)__kernel_` variables as allowable in code.
- after (initial proposal)
- after (latest)
> `kernel`
> Determines whether `l3doc` treats internal functions and variables belong to `kernel` module as allowable in code, for instance `\__kernel_tl_to_str:w`, `\c__kernel_expl_date_tl`, and `\l__kernel_expl_bool`.
> Document default l3doc class options

- l3kernel/l3prg.dtx
I'm not sure why I didn't think of that when I sped up `\group_align_safe_begin:`, but this here speeds up `\group_align_safe_end:` in the same way.
> Faster align_safe_end

- l3kernel/l3clist.dtx
- l3kernel/l3debug.dtx
- l3kernel/l3fp-assign.dtx
- l3kernel/l3kernel-functions.dtx
- l3kernel/l3prop.dtx
- l3kernel/l3regex.dtx
- l3kernel/l3seq.dtx
- l3kernel/l3sort.dtx
- l3kernel/l3str-convert.dtx
- l3kernel/l3str.dtx
- l3kernel/l3sys.dtx
- l3kernel/l3tl-analysis.dtx
- l3kernel/l3tl-build.dtx
- l3kernel/l3tl.dtx
Together with 1f45ced8bc3c881736ad153a3debf8ada275608b (Revert to \\\_\_kernel\_tl\_set:Nx, 2024-01-10), now the effect of 9dd74fcfd4efff26c479fe78890021d3334cf94f (Swiitch \\\_\_kernel\_tl\_(g)set:Nx to :Ne, 2023-09-25) were totally reverted.
> Revert to \__kernel_tl_gset:Nx

- l3kernel/doc/l3styleguide.tex
- l3kernel/l3doc.dtx
- l3kernel/l3quark.dtx
- l3packages/l3doc/examples/testing.dtx
- xpackages/xor/xotrace.ins
Being reminded by 1b79c4e3 (Update expl3 for DocStrip support of @@ convention, 2023-10-09).
> Mention DocStrip instead of l3docstrip

- l3kernel/l3keys.dtx
This ends up being a couple of marginally-related changes to `l3keys.dtx`, starting from the observation that comparing groups was being done in a messy way due to too much freedom in what their name can contain.
- The `groups` comma list argument of `\keys_set_groups:nnn` and related functions was allowed to be for instance `name 1, name 2, { name with ,,,, commas }` where the last one would end up containing leading/trailing spaces an commas.  This made comparisons more difficult, requiring a loop over the clist of groups.  To speed this up I opted to apply `\tl_to_str:n` right away, which makes sure that group names are strings without leading/trailing spaces nor commas.  Comparison is easier.
- The documentation used the word group or subgroup in a few places to talk about the …
> Small cleanup in l3keys

- l3kernel/CHANGELOG.md
- l3kernel/doc/source3body.tex
- l3kernel/l3debug.dtx
- l3kernel/l3flag.dtx
- l3kernel/l3fp-symbolic.dtx
- l3kernel/l3fp-traps.dtx
- l3kernel/l3fp.dtx
- l3kernel/l3keys.dtx
- l3kernel/l3pdf.dtx
- l3kernel/l3regex.dtx
- l3kernel/l3str-convert.dtx
- l3kernel/l3token.dtx
- l3kernel/testfiles/m3flag001.lvt
- l3kernel/testfiles/m3flag001.tlg
- l3kernel/testfiles/m3flag002.lvt
- l3kernel/testfiles/m3flag002.tlg
- l3kernel/testfiles/m3fp-traps001.lvt
Flags are the only variable type that can be modified in an expansion-only context (without using LuaTeX).  They are currently named by an `n`-type string like `fp_overflow` and the present changes allow more LaTeX3 names such as `\l_fp_overflow_flag`.  (In fact, the implementation is such that both the `n`-type flag `fp_overflow` and the `N`-type flag `\l_fp_overflow_flag` have the same value since they use the same underlying csnames.)
There should be a slight speed up from having fewer tokens to move around, but the main motivation is to make flags more similar to other variables.  The goal here is to eventually deprecate `n`-type flag variables.  It is not currently possible to deprecate them since flags are used quite a lot despite the numerous warnings in the documentation that they …
> Implement N-type flag variables

- l3kernel/l3file.dtx
Changes `\cs{file name}` to `\meta{file name}` in l3file.dtx
Following muzimuzhi's suggestion, the description for `\file_if_exist:n(TF)` has been reworded to more closely match `\file_get_full_name:nN(TF)` and `\file_full_name:n`.
> fix typo in l3file.dtx

- l3kernel/CHANGELOG.md
- l3kernel/l3coffins.dtx
- l3kernel/testfiles/m3coffins001.luatex.tlg
- l3kernel/testfiles/m3coffins001.ptex.tlg
- l3kernel/testfiles/m3coffins001.tlg
- l3kernel/testfiles/m3coffins001.uptex.tlg
- l3kernel/testfiles/m3coffins001.xetex.tlg
This PR fixes local assignments (`\prop_put:cnn`) to global variables in `\vcoffin_gset:Nnn` and `\vcoffin_gset:Nnw`.
> Fix inconsistent local/global assignments in l3coffins

- l3kernel/doc/source3body.tex
The last part in `interface3.pdf` (also the second last part in `source3.pdf`) has been empty since the removal of empty `l3candidates.dtx`.
See 5d5f252e (Remove l3candidates, 2024-01-10).
> Drop empty part "Removals"

- l3kernel/CHANGELOG.md
- l3kernel/l3doc.dtx
This incorporates latex3/latex2e@60a6a368 (Prevent time wasted debugging latex3/latex2e@50f5256, 2021-10-20) by @PhelypeOleinik, with some modification.
Following https://github.com/latex3/latex2e/pull/1270#discussion_r1485597939, I find this is one of l3doc fixes/improvements made only in latex2e, hence not yet incorporated into `l3doc.dtx`.
Questions:
- Does `\DocInput` need a similar check? Currently `\DocInclude` uses `\DocInput` internally.
- Would `\DocInclude`/`\DocInput` be used in groups, so we need to compare the values of `\tex_currentgrouplevel:D` at the beginning and end of command, instead of simply checking if it's zero at the end?
- I noticed `\DocInclude` is not documented, and it seems it's inherited from `ltxdoc.cls`. Is `\DocInclude` an official `l3doc` command, or …
> Check missing `\endgroup` at the end of `\DocInclude`

- l3kernel/CHANGELOG.md
- l3kernel/doc/interface3.tex
- l3kernel/l3doc.dtx
- l3kernel/testfiles-l3doc/test.lvt
- l3kernel/testfiles-l3doc/test.tlg
To avoid setting `\texttt` twice, commands based on `\meta` (e.g., `\Arg`) now use internal `\__codedoc_meta:n`.
This incorporates a patch to `\meta` added to interface3.tex only, made in c1473aab (Standardise "fp expr", etc., in sources, 2021-07-28).
> Typeset `\meta` in `\texttt`

- l3kernel/l3doc.dtx
This PR fixes a problem pointed out by @blefloch in https://github.com/latex3/latex3/pull/1448#discussion_r1485972439.
Relevant logic is not covered by any tests so skipping ci is not more dangerous.
> Expand a msg arg [ci skip]

- l3kernel/l3token.dtx
This PR corrects a typo introduced in fe2ec419 (Extend docs for \char_set_active_eq:NN (see #1437), 2024-02-09).
> Typo, `\cs{char_set_active_eq:NN}` -> `:nN`

- l3kernel/l3debug.dtx
- l3kernel/l3kernel-functions.dtx
This avoids a warning raised when building `source3.pdf`:
```tex
LaTeX Warning: Label `doc/function////kernel/chk/cs/exist:N' multiply defined.
```
Closes #1447.
> Move docs of l3debug kernel functions to l3kernel-functions

- l3kernel/doc/l3prefixes.csv
`fontspec` is moved from https://github.com/wspr/fontspec to https://github.com/latex3/fontspec  around 2022.
> Update info of prefix "fontspec"

- l3kernel/build.lua
- l3kernel/doc/interface3.tex
- l3kernel/doc/l3styleguide.tex
- l3kernel/doc/l3syntax-changes.tex
- l3kernel/doc/l3term-glossary.tex
- l3kernel/doc/source3.tex
This fixes a regression introduced in ecccd76a (Avoid code duplicate in tagging routine, 2023-12-11) that made tex files in `./l3kernel/doc` not tagged.
The original logic was
```lua
if string.match(file,"%.dtx$") or string.match(file,"%.tex$") then
return string.gsub(content,
"\n(%%*%s*)\\date{Released " .. iso .. "}\n",
"\n%1\\date{Released " .. tagname .. "}\n")
elseif string.match(file, "%.md$") then
-- ...
end
```
> Fix tagging for tex files

- l3kernel/l3basics.dtx
Problems solved:
- `<token_1>` and `<token_2>` notations used only once
- `<true code>` not well defined
- typo
- legal construct not covered:
```
\def\x{xYES\else: NO\fi:}
\def\y{yNO\else: YES\fi:}
\if:w x\x
\if:w x\y
```
> \if:w documentation

- l3kernel/testfiles/m3clist002.lvt
- l3kernel/testfiles/m3clist002.tlg
- Fix unwanted inconsistent local/global assignments.
- Fix use of `\tl_use:N` on clist variables.
> Correct m3clist002 test

- l3kernel/l3prop.dtx
- l3kernel/testfiles/m3prop008.lvt
- l3kernel/testfiles/m3prop008.tlg
Now applying these operations to an undefined prop or prop that came up from incorrect tl operations will raise an error and define the prop essentially with \prop_new:N.  This avoids cascading errors and errors that are incomprehensible to the end-user.
> Improve error recovery for prop get/put/pop etc with invalid prop

- l3kernel/CHANGELOG.md
- l3kernel/l3doc.dtx
- l3kernel/testfiles-l3doc/github-1398.tlg
- l3kernel/testfiles-l3doc/test.lvt
- l3kernel/testfiles-l3doc/test.tlg
Fixes #730
Before
After
Currently the color of `TF` of public conditionals is also changed. Is this change welcome?
> Typeset `TF` of internal conditionals in current color

- build-config.lua
- l3packages/xtemplate/xtemplate.dtx
The updated date (2024-02-20) in `xtemplate.dtx` is the same as those in other `l3packages` packages.
```
$ rg --no-heading '^\s*\\ProvidesExpl' -g 'l3packages/**/*.dtx' -g '!examples'
l3packages/xparse/xparse.dtx:1082:\ProvidesExplPackage{xparse}{2024-02-20}{}
l3packages/xtemplate/xtemplate.dtx:707:    \ProvidesExplPackage{xtemplate}{2024-02-20}{}
l3packages/l3keys2e/l3keys2e.dtx:157:\ProvidesExplPackage{l3keys2e}{2024-02-20}{}
l3packages/xfp/xfp.dtx:174:\ProvidesExplPackage{xfp}{2024-02-20}{}
```
> Tag indented \ProvidesExpl... lines

- build-config.lua
- l3experimental/l3draw/build.lua
- l3experimental/l3graphics/build.lua
- l3experimental/l3opacity/build.lua
- l3kernel/config-backend.lua
Test suites which don't check on `etex-dvips` and `etex-dvisvgm` special formats are not influenced.
> Move `specialformats` settings to root config

- l3experimental/CHANGELOG.md
- l3experimental/l3draw/l3draw-softpath.dtx
- l3experimental/l3draw/testfiles/m3draw003.etex-dvips.tlg
- l3experimental/l3draw/testfiles/m3draw003.etex-dvisvgm.tlg
- l3experimental/l3draw/testfiles/m3draw003.lvt
- l3experimental/l3draw/testfiles/m3draw003.tlg
- l3experimental/l3draw/testfiles/m3draw003.uptex.tlg
- l3experimental/l3draw/testfiles/m3draw003.xetex.tlg
Fixes #1492.
The Changelog entry may be improved, and might conflict with #1490.
Theoretically only one of the two markers needs to be patched quark-like, but I changed both of them.
> Fix softpath markers with the same meaning

- l3kernel/l3file.dtx
This function was missed when `\iow_shell_open:Nn` was added in 8c2338d. I based the implementation on `\__kernel_ior_open:Nn`.
This closes #1515.
> Implement \__kernel_iow_open:Nn

- l3kernel/l3kernel-functions.dtx
Also update example function which uses `\__kernel_ior_open:Nn`.
See https://github.com/latex3/latex3/pull/1516.
Sorry for a new PR. When I found this missing piece, #1519 was already merged. :)
> Document \__kernel_iow_open:Nn in l3kernel-functions.dtx

- l3kernel/CHANGELOG.md
- l3kernel/l3doc.dtx
This is the change to `l3doc.cls` in latex3/latex2e@9a544750 (Capture newlines as \obeyedline in ltcmd, 2024-03-20).
> Adapt `l3doc` for `ltcmd` change to handling of newlines

- l3kernel/CHANGELOG.md
- l3kernel/l3cctab.dtx
- l3kernel/testfiles/m3cctab002.tlg
- l3kernel/testfiles/m3cctab002.xetex.tlg
- l3kernel/testfiles/m3regex005.tlg
- l3kernel/testfiles/m3regex005.xetex.tlg
The previous merged PR #1509 suspended debugging too much, especially the debugging for `<category code set up>` in `\cctab_const:Nn <category code table> {<category code set up>}` was suspended.
This PR narrows the scope to only suspend `\intarray_new:Nn` used in non-LuaTeX implementation of `\__cctab_new:N`.
This also avoids duplicate inconsistent local/global assignment errors raised by `\cctab_new:N` and unwanted logging written by `\cctab_begin:` in non-LuaTeX engines, see `.tlg` changes.
> Narrow scope of debug suspending for \cctab_const:Nn

- l3kernel/l3file.dtx
- Before: `\ior_get_term:nN <prompt> <token list variable>`
- After: `\ior_get_term:nN {<prompt>} <token list variable>`, added braces around `<prompt>`.
> Doc typo, \meta -> \Arg

- l3kernel/l3prop.dtx
The second occurrences of `(N|c)eV` should be `(N|c)ee`. Lists of variants in `\cs_generate_variant:Nn` were correct.
Introduced in eacd32f5 (Round-out vartiant set for \prop_(g)put_if_not_in:Nnn, 2024-05-07).
> Fix typos in list of variants

- l3kernel/l3file.dtx
- l3kernel/l3int.dtx
- l3kernel/l3seq.dtx
- l3kernel/l3tl.dtx
Since l3kernel 2022-02-21 relevant primitives are all marked required, thus "This is not available in older versions XeTeX." docs can be removed.
See df25bca5 (Update primitive requirements docs, 2022-02-21).
> Drop outdated docs

- l3kernel/l3box.dtx
- l3kernel/l3color.dtx
- l3kernel/l3fp.dtx
- l3kernel/l3keys.dtx
- l3kernel/l3pdf.dtx
- l3kernel/l3text.dtx
This PR fixes miscellaneous typos and missing punctuation that I noticed while reading `interfaces3.pdf` back-to-back.
I manually ran `l3build doc` and eyeballed `interfaces3.pdf` to ensure that these changes do not produce poor line breaks.
> Fix miscellaneous typos and missing punctuation in the docs

- l3kernel/doc/l3prefixes.csv
I hope it's okay to do 2 at once.
I wonder if it would be better to have kind of overview page for the older ptxcd and the ptxtools prefix. If you think that would be useful I'd create something like that. as it's actually spanning across multiple projects which by design would not overlap.
> Register ptxtools + zugferd prefix

- l3kernel/CHANGELOG.md
- l3kernel/l3deprecation.dtx
- l3kernel/l3str.dtx
Sync their implementation with that of `\text_titlecase:n(n)`.
> Fix implementation of deprecated `\tl_mixed_case:n(n)`

- l3kernel/CHANGELOG.md
- l3kernel/doc/source3body.tex
- l3kernel/expl3.dtx
- l3kernel/l3quark.dtx
> Add quark (`\q_`) and scan mark (`\s_`) prefixes to naming scheme

- l3packages/CHANGELOG.md
- l3packages/xparse/testfiles/xparse009.lvt
- l3packages/xparse/testfiles/xparse009.tlg
- l3packages/xparse/xparse.dtx
> Support 'opt' cmds in \GetDocumentCommandArgSpec

- l3kernel/CHANGELOG.md
- l3kernel/l3basics.dtx
- l3kernel/l3doc.dtx
- l3kernel/l3expan.dtx
- l3kernel/testfiles-l3doc/github-1577.lvt
- l3kernel/testfiles-l3doc/github-1577.tlg
> Fix handling of `ltcmd` newlines (`\obeyedline`) in l3doc

- l3kernel/doc/source3body.tex
This PR makes sentences between `description` envs consisting of mostly one-liner items more visible (in `interface3.pdf`, sec. 1.1 Naming functions and variables), by setting `enumitem` options to enlarge left margin of those `description` envs.
`enumitem` is loaded by `l3doc`.
| Before | After |
|--------|-------|
| ![image](https://github.com/user-attachments/assets/01dde00e-2d90-4bd2-8be4-9fb143cc77db) | ![image](https://github.com/user-attachments/assets/eba1b28c-46f8-4704-8ca0-f1a0f66f73d8) |
The first `description` env for function argument specifiers are not modified, since items in it all span multiple lines.
| Beginning | Ending |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/c6093b7b-4522-4d29-bd4c-4bfbd4d5c070) | …
> Enlarge left margin of description envs with one-liner items

- l3kernel/CHANGELOG.md
- l3kernel/l3doc.dtx
- l3kernel/testfiles-l3doc/test.lvt
- l3kernel/testfiles-l3doc/test.tlg
Fixes #1585.
Output of `./l3kernel/testfiles-l3doc/test.lvt`:
| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/a8f827bc-2bc9-4007-9dc3-ab3ca291b47c) | ![image](https://github.com/user-attachments/assets/2dcaeb19-0a78-4b62-a780-055150793360) |
> Increase outdent of long function names

- l3kernel/l3clist.dtx
Changes `\meta` to `\Arg` for `\clist_use:nnnn` and `\clist_use:nn`.
Also fixes the referenced arg in `\clist_if_empty:nTF` from `clist var` to `comma list`.
I also noticed there's not consistency in how the `N` and `n` clist commands are documented. Some of them are documented together but only the `N` type is shown, e.g. `\clist_if_in:...`, `\clist_map_function:...`, etc. Some are documented together and both are shown, e.g. `\clist_map_tokens:...`, `\clist_rand_item:...`. And some are documented separately, e.g. `\clist_use:...`, `\clist_show:...`. Maybe this is intentional, just thought I'd point it out.
> fix arg type for \clist_use:nnnn

- l3kernel/CHANGELOG.md
- l3kernel/l3doc.dtx
Fixes:
* in l3doc two global bool are set locally. 
* With lualatex T1-encoding is used, this switches to TU-encoding. 
(dates are not changed as I think that is done at a release?)
> correct global boolean, use TU with lualatex

- l3kernel/CHANGELOG.md
- l3kernel/l3clist.dtx
- l3kernel/l3color.dtx
- l3kernel/l3file.dtx
- l3kernel/l3int.dtx
- l3kernel/l3intarray.dtx
- l3kernel/l3str-convert.dtx
- l3kernel/l3str.dtx
- l3kernel/l3sys.dtx
- l3kernel/l3text.dtx
(I hope this is okay all in one PR.)
Various documentation improvements for interface3, including
- manual line breaks for long argument specs
- using e.g. `name_1` over `name1` or `name~1`
- fixing several `\meta` to `\Arg` and vice versa
- using `tl var` over just `tl`; also `tokens` over `tl` if `n`-type
- using `integer` over `int` (only occurs once)
- using `seq var` over `seq`
- documenting `\str_item:cn`
> various documentation improvements

- l3kernel/l3names.dtx
Removed three definitions in l3names that simply repeat other definitions (at lines 587, 1178, and 1207). No other duplicates are found.
> Cleaup duplicate definitions in l3names

- l3kernel/l3fp.dtx
Removes an extra brace in the example under `\fp_set_function:nnn`.
> remove extra brace in l3fp.dtx

- .github/workflows/cache.yaml
- .github/workflows/deploy.yaml
- .github/workflows/main.yaml
Ubuntu 20 image is closing down
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#ubuntu-20-image-is-closing-down
> Run CI on ubuntu-latest

- l3kernel/l3tl.dtx
Maybe `l3doc` could provide a new command for this kind of markup, like
```tex
% b for braced; \arg is taken by amsmath as one of math operator commands
\NewDocumentCommand\barg{m}{\texttt{\char`\{} #1 \texttt{\char`\}}}
```
Before
After
> Typeset curly braces in ttfamily

- l3kernel/l3str.dtx
The `Ne` variant is incorrectly documented twice and the `ce` variant is missing. This fixes that.
> fix \str_put_right:ce doc

- l3kernel/l3seq.dtx
Fixes #1645.
l3kernel once did an overall x-to-e conversion, then reverted `\__kernel_tl_(g)set:Ne` to `:Nx`, which may result in quite some wrong expansion types used in code comments.
> Update expansion type in comments, s/e/x/g

- l3kernel/doc/source3body.tex
- l3kernel/l3basics.dtx
- l3kernel/l3fparray.dtx
- l3kernel/l3int.dtx
- l3kernel/l3keys.dtx
- l3kernel/l3msg.dtx
- l3kernel/l3pdf.dtx
- l3kernel/l3prg.dtx
- l3kernel/l3prop.dtx
- l3kernel/l3regex.dtx
- l3kernel/l3seq.dtx
This standardizes several argument types across interface3. I didn't try to deal with `⟨bool expr⟩` vs. `⟨boolean expression⟩`, `⟨int expr⟩` vs. `⟨integer expression⟩`, or `⟨tokens⟩` vs. `⟨token list⟩` since there were too many instances of each to pick one as the clearly intended choice.
> standardize argument types in interface3

- l3kernel/CHANGELOG.md
> Escape '#'s in ChangeLog

- l3kernel/l3bootstrap.dtx
- l3kernel/l3luatex.dtx
- l3kernel/l3regex.dtx
- l3kernel/l3str-convert.dtx
- l3kernel/l3tl.dtx
- l3kernel/l3token.dtx
02d28bb1 (Use a UTF-8 char, 2024-12-28)
Uses of 'regime' in `./l3trial` are not replaced.
> Use a UTF-8 char, continued

- README.md
Reading the commit message of 2d3c3e35 (Step copyright (l3kernel), 2025-01-01), it seems to me that the copyright in the top-level README can be updated too.
> We can be sure there will be changes in l3kernel in 2025 - other parts may
or may not change, so copyright update there has to wait for at least one
'real' commit.
> Step copyright (top-level README)

- l3kernel/CHANGELOG.md
- l3kernel/l3int.dtx
For `clist`, `tl`, `seq`, etc. there is a `map_tokens:` variant of the mapping functions. For `int` none such version exists. This PR adds it at almost zero cost (just three new control sequences).
I also added a micro-optimisation to the internal used by both `\int_step_function:nnnN` and `\int_step_tokens:nnnn`.
> Add int_step_tokens:nnnn functions

- l3kernel/CHANGELOG.md
Keep the order of 'Added', 'Changed', then 'Fixed'.
> Re-order types of changes in Changelog

- l3kernel/l3doc.dtx
`The~\LaTeX~Project~team`, which is equal to `The \LaTeX Project team` out of expl3 syntax, will output "The LaTeXProject team", while `The~\LaTeX{}~Project~team` could output "The LaTeX Project team". Obviously, the latter one is correct.
> A small carelessness in the manual of l3doc

- l3experimental/l3opacity/l3opacity.dtx
The `variable` environment will swallow an argument, or I couldn't successfully compile the `.dtx` file.
> A carelessness in the implementation part of `l3opacity.dtx`

- l3backend/build.lua
The common `./build-config.lua` defines a common `update_tag()` and an empty hook `update_tag_extra()` for customization. Among all the modules in this repository, `./l3backend/build.lua` is the only one which defines its own `update_tag()`.
Since the two `update_tag()`s are more similar than not, this PR drops the `update_tag()` in `./l3backend/build.lua` and moves the customization in `update_tag_extra()`.
Tested locally by executing `l3build tag 2025-03-01` in `./l3backend`.
<details><summary>Comparison on the two <code>update_tag()</code>s.</summary>
<p>
```diff
diff --git a/build-config.lua b/l3backend/build.lua
index 4a719bd..3a508b5 100644
--- a/build-config.lua
+++ b/l3backend/build.lua
@@ -1,43 +1,44 @@
-- Detail how to set the version automatically
function …
```
> Use common `update_tag()` for l3backend

- l3kernel/expl3.dtx
- l3kernel/l3clist.dtx
- l3kernel/l3color.dtx
- l3kernel/l3sys.dtx
- l3kernel/l3tl.dtx
- l3kernel/l3unicode.dtx
All except for the 'these' -> `that` one were caught by [`typos`](https://github.com/crate-ci/typos), command [`typos l3kernel/*.dtx`](https://github.com/crate-ci/typos).
The `typos` cli provides a GitHub Action, which can be used as `uses: crate-ci/typos@v1`. A whitelist is needed if we'd like to add it to CI.
> Correct typos

- l3backend/l3backend-opacity.dtx
- l3experimental/l3draw/l3draw.dtx
- l3kernel/l3box.dtx
- l3kernel/l3color.dtx
- l3kernel/l3doc.dtx
- l3kernel/l3fp-round.dtx
- l3kernel/l3luatex.dtx
- l3kernel/l3text-case.dtx
- l3trial/l3doc/examples/basics.dtx
- l3trial/l3doc/examples/indexing.dtx
- l3trial/xbox/xbox.dtx
It all started from spotting an unnecessary empty line introduced by https://github.com/latex3/latex3/commit/6908dd8636260c174b0afe7a824e371981d06f7a (more specifically [here](https://github.com/latex3/latex3/commit/6908dd8636260c174b0afe7a824e371981d06f7a#diff-8d622406df5e749465119bf293218a7296fdeb18c7a74116ac065861413af970R126)).
> Drop unnecessary empty lines

- l3kernel/l3file.dtx
- l3kernel/l3fp-aux.dtx
- l3kernel/l3fp-basics.dtx
- l3kernel/l3fp-expo.dtx
- l3kernel/l3fp-extended.dtx
- l3kernel/l3fp-parse.dtx
- l3kernel/l3fp-round.dtx
- l3kernel/l3fp-trig.dtx
- l3kernel/l3regex.dtx
- l3kernel/l3skip.dtx
- l3kernel/l3tl-analysis.dtx
- l3kernel/l3tl.dtx
Similar to #1671, this PR replaces not only the ";" characters but also the words "semicolon", "semicolons", "semi-colon" with `\cs{@@_sep:}`, in more dtx files.
An `l3fp` internal function `\@@_parse_return_semicolon:w` is also renamed to `\@@_parse_return_sep:w`.
> Replace remaining ";" and "semi(-)colon" in comments

- l3kernel/l3expan.dtx
After 0b063745 (Round out \exp_args:N... lists (closes #<span></span>1731), 2025-04-28), the old model function used in the syntax block, `\exp_args:NNoo` became the 7th (was 4th before that) on the longer list.
https://github.com/latex3/latex3/blob/0933a0fc292a0ed5ed996f7cf922bc3184d3ad89/l3kernel/l3expan.dtx#L511-L519
This PR replaces it with the top one, `\exp_args:NNno`.
> Update model function for an `\exp_args:...` documentation group

- l3kernel/CHANGELOG.md
- l3kernel/l3luatex.dtx
Fixes https://github.com/latex3/latex3/issues/1597 . Uses the patch there.
I don't think there's any disadvantage (for users who doesn't use precompiled preamble, the only visible difference is that in the second run `register_luadata` is also available, but if they just don't use it then there's no difference)
> Preserve intarray across multiple dumps

- l3kernel/doc/l3prefixes.csv
Not really sure you want all/any of these.
CTAN packages:
- adforn: adforn
- adfsymbols: adfarrows (for pkg adfarrows), adfbullets (for pkg adfbullets)
- baskervaldadf: baskervald
- berenisadf: berenis
- cfr-lm: clm
- chronos: chronos
- electrumadf: electrum
- fillwith: fillwith
- libris: libris
- nfssext-cfr: exfs (matches the 2e prefix from nfssext used by nfssext-cfr)
- prooftrees: prooftrees
- romandeadf: romande
- venturisadf: venturis (for pkg venturis), venturisii (for pkg venturis2), venturisold (for pkg venturisold)
Public but not yet CTAN:
- fixtounicode: fixtounicode
> Register various prefixes

- l3kernel/l3color.dtx
- l3kernel/testfiles/m3color003.lvt
- l3kernel/testfiles/m3color003.tlg
As wished in https://github.com/latex3/xcolor/issues/26, I wrote a function converting from some LCh color space (name Oklch based on [Oklab](https://bottosson.github.io/posts/oklab)) to the standard RGB color space. That seemed easier to do with l3color, so I did it here.
IMHO it would make much sense to allow mixing colors in Oklab, and thus provide it as a core color model. Though, that seems better suited in a package like xcolor outside the kernel. So, likely I will also port the code to xcolor after all.
> Support Oklab and Oklch as interface color models

- .github/typos.toml
- support/lualatex.ini
Exclude all files in the top-level `./support` dir, except for the `regression-test.cfg`. This reverts two "behaviour" -> "behavior" corrections made to `./support/lualatex.ini`.
Exclude historical package versions like `xtemplate-2023-10-10.sty`.
> Exclude more files from spelling check

- l3kernel/l3color.dtx
As noted in https://github.com/latex3/latex3/pull/1500#issuecomment-2896657265, the Oklab implementation does less than some people may assume. Maybe some day someone cares to implement the rest.
Typst, by the way, seems to support all kinds of fuss with color spaces as of [some 2023 blog post](https://typst.app/blog/2023/color-gradients). Some pseudo code for gamut clipping may be found in [CSS Color Module Level 4](https://www.w3.org/TR/css-color-4/#ok-lab) (it has some some weird behavior around sRGB’s primary blue `#0000ff`, but that is mostly harmless).
> Document restrictions of oklab implementation

- l3kernel/CHANGELOG.md
- l3kernel/l3prop.dtx
- l3kernel/l3tl.dtx
To sync with its new, speed-up implementation, see 0fdf1714 (speed up trim spaces (#<span></span>1679), 2025-02-04).
> Update `\tl_trim_spaces:n` comment

- l3kernel/l3expan.dtx
- l3kernel/l3text.dtx
- Update sample syntaxes for `\exp_...` doc groups
- Correct typos for `\text_(words)_map_tokens:nn` docs
> Minor doc improvement

- l3kernel/l3.ins
- l3kernel/l3basics.dtx
- l3kernel/l3file.dtx
It seems now `\iow_log:e` and `\iow_term:e` are no longer needed in bootstrapping.
Starting from finding the `\iow_show:e` was unnecessarily defined with `\cs_set...` rather than `\cs_new...`, I then was curious about how `\iow_(log|term):e` were used in bootstrapping and finally found they are not needed now.
`\iow_(log|term):x` were added to `l3basics.dtx` by d912fc688d ([Big bang] Complete l3basics: some rearrangements made, 2011-05-09), to support expl3 debugging at that time (`\chk_if_free_cs:N`). As now debugging is extracted to `l3debug.dtx` and the debugging configuration can only be loaded after `expl3-code.tex`, the requirement for having `\iow_(log|term):(e|x)` in bootstrapping had disappeared.
> Drop `\iow_log:e` and `\iow_term:e` from bootstrapping

- l3kernel/l3doc.dtx
Not really a correction, because DocStrip converts both `_@@` and `__@@` to `__<module>`. Therefore no code behavior is changed.
> Correct a l3doc var name

- l3kernel/doc/l3prefixes.csv
This PR normalizes the dates in the columns "First registered" and "Last update" of the file `l3prefixes.csv` to the YYYY-MM-DD format. This PR updates just a single row for the package _piton_, which used the format DD/MM/YYYY in these columns before this PR. This improves the ability of external tools, [such as _expltools_][1], to automatically parse this file.
[1]: https://github.com/Witiko/expltools/blob/91740bdb325860197a2c72479d2b407b2f517d30/explcheck/src/generate-explcheck-latex3.lua#L221-L223
> Consistently use the YYYY-MM-DD format in `l3prefixes.csv`
